### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by drusellers** [NickMcBurney/storybook-vue3-router#53]
<img width="777" alt="CleanShot 2023-08-02 at 16 50 00@2x" src="https://github.com/NickMcBurney/storybook-vue3-router/assets/63355/de8383b3-7976-4995-926b-1dbcc90d4012">

Is there a recommended next package? If so it would be handy to have it mentioned at the top of the various docs.

**Comment by NickMcBurney** [comment]
This is due to a mistake I made. **This package is not deprecated** 

I accidentally published a v4.x version when it should have been 3.x. Because there is a package out there which depends on this package (and uses poor version selection I could not delete the 4.x version from npm repository). I took decision to deprecate 4.x but 3.x is not deprecated

**Comment by NickMcBurney** [comment]
v4.x is now released as a working version and depreciation notice should be removed.
